### PR TITLE
Replace example values in mcmod.info

### PR DESCRIPTION
**Pull request by SethWilliamson**
The modinfo file was still the Forge example.

The preferred versioning schema is {MCVer}-{[SemVer](http://semver.org/)}[-branch/beta/alpha/whatever]

As I recall it started with a [tweet from LexManos](https://twitter.com/LexManos/status/591356697911762944) of Forge. There was some dialog in various places, but the result is most authors have voluntarily adopted the format. You may want to update your build.gradle to follow suit.

### CODE REVIEW

**Comment by SethWilliamson** [comment]
Regarding versioning, as I recall it started with a tweet from LexManos of Forge. There was some dialog in various places, but the result is most authors have voluntarily adopted the format.

https://twitter.com/LexManos/status/591356697911762944

**Comment by cubex2** [comment]
The modinfo file is actually not used. The metadata is set in the constructor of BFDummyContainer. I'm not sure if that file is required for a mod to be loaded. If not, it should better be removed.

**Comment by SethWilliamson** [comment]
The example template file is being packaged and included in the release jars. Opening the jars with an archive tool shows the file in there. 

You're right that it isn't required for functionality, but it is used for informational purposes in some applications and doesn't hurt to populate it.  For example, I noticed the issue because your mod is being listed as "Example Mod" in the MultiMC launcher.

**Comment by cubex2** [comment]
Didn't have external applications in mind. It's a good idea to have it updated then.

**Pull request merged**
